import TodosPage from 'src/View/Todo';
import Head from 'next/head';
import {NextPage} from 'next';

const Todos: NextPage = () => {
  return (
    <>
      <Head>
        <title>Todos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodosPage />
    </>
  );
};

export default Todos;
