import {useAuth} from 'src/context/AuthContext';
import Head from 'next/head';
import Login from './auth/login';
import Dashboard from './dashboard';

export default function Home() {
  const {currentUser} = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentUser ? <Login /> : null}
      {!!currentUser ? <Dashboard /> : null}
    </>
  );
}
