import {useAuth} from 'src/context/AuthContext';
import Head from 'next/head';
import Login from './auth/login';
import Dashboard from './dashboard';
import {useRouter} from 'next/router';
import {useEffect} from 'react';

export default function Home() {
  // const {currentUser} = useAuth();

  const router = useRouter();
  useEffect(() => {
    router.replace('/dashboard');
  }, [router]);
  return null;

  // return (
  //   <>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <meta name="viewport" content="width=device-width, initial-scale=1" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     {!currentUser ? <Login /> : null}
  //     {!!currentUser ? <Dashboard /> : null}
  //   </>
  // );
}
